easy_admin:
    formats:
        date: 'd/m/Y'
        time: 'H:i'
        datetime: 'd/m/Y H:i:s'
    entities:
   
        User:
            class: App\Entity\User
            label: Utilisateur  
            list:
                fields:
                    - property: email
                      label: Email 
                    - property: lastName
                      label: Nom
                    - property: firstName
                      label: Prénom  
                    - property: side
                      label: side               
                    - property: birthdate
                      label: Date de naissance
                      type: date
                    - property: enabled
                      label: Compte activé
                    - property: createdAt
                      type: datetime
                      label: Date de création
                      type_options:
                        disabled: true
                        widget: single_text
                    - property: roles
                      label: Rôles
                
                      
            form:
                label: Utilisateur
                form_options: { validation_groups: [] }

                fields:
                    - property: email
                      label: Email
                    - property: lastName
                      label: Nom
                      type: text
                    - property: firstName
                      label: Prénom
                      type: text
                    - property: Side
                      label: Side
                      type: 'choice'
                      type_options:
                          mapped: true
                          choices: { 'Jedi': 1, 'Sith': 0 }  
                    - property: birthdate
                      type: date
                      label: Date de naissance
                      type_options:
                        widget: single_text
                        input: datetime
                    - property: enabled
                      label: Compte activé
                    - property: 'roles' 
                      type: 'choice'
                      type_options:
                          mapped: true
                          expanded: true
                          multiple: true
                          choices: { 'Caissière': 'ROLE_CASHIER', 'Client': 'ROLE_USER', 'Administeur': 'ROLE_ADMIN' }
                    
            edit:
                item_permission: 'ROLE_ADMIN'        
            new:
                fields:
                    - property: password
                      type: text
                item_permission: 'ROLE_ADMIN'
            delete:
                item_permission: 'ROLE_ADMIN'


        Ticket:
            class: App\Entity\Ticket
            label: Billet
            list:
                fields:                    
                    - property: user
                      label: Utilisateur
                    - property: serial
                      label: Numéro de série                    
                    - property: buyAt
                      label: Date d'achat
                      type_options:
                        widget: single_text
                        input: datetime
                        disabled: true
                    - property: used
                      label: Utilisée
                      type: boolean
                      
            form:
                label: Billet
                form_options: { validation_groups: [] }
                fields:
                    - property: user
                      label: Utilisateur    
            edit:
                item_permission: 'ROLE_ADMIN'
                fields: 
                    - property: used
                      label: Utilisée
            new:
                item_permission: 'ROLE_ADMIN'
            delete:
                item_permission: 'ROLE_ADMIN'

        Gift:
            class: App\Entity\Gift
            label: Cadeau
            list:
                fields:
                    - property: title
                      label: Titre
                    - property: price
                      label: Prix
                    - property: picture
                      label: Image
                      type: image
                      base_path: '/images/gifts/'
            form:
                label: Cadeau
                form_options: { validation_groups: [] }
                fields:
                    - property: title
                      label: Titre
                    - property: price
                      label: prix
                    - property: picture
                      label: Image
                      type: file_upload
                      type_options:
                          upload_dir: public/images/gifts/
                          
                    - property: enabled
                      label: Activé 
                      
                      
                                        
            edit:
                item_permission: 'ROLE_ADMIN'
            new:
                item_permission: 'ROLE_ADMIN'
            delete:
                item_permission: 'ROLE_ADMIN'

        Card:
            class: App\Entity\Card
            label: Carte
            list:
                fields:
                    - property: user
                      label: Utilisateur  
                    - property: serial
                      label: Numéro de série
                    - property: credits
                      label: Crédits
                    - property: expireCreditsAt
                      label: Date de expiration de crédit
                      type: date
                                      
            form:
                label: carte
                form_options: { validation_groups: [] }
                fields:
                     - property: user
                       label: Utilisateur
                     - property: credits
                       label: Crédits                  
            edit:
                item_permission: 'ROLE_ADMIN'
            new:
                item_permission: 'ROLE_ADMIN'
            delete:
                item_permission: 'ROLE_ADMIN'


        Booking:
            class: App\Entity\Booking
            label: Réservation
            list:
                fields:
                    - property: user
                      label: Utilisateur
                    - property: serial
                      label: Numéro de série  
                    - property: Pseudo
                      label: Pseudo 
                      type: text
                    - property: Score
                      label: Score
                      type: text                    
                    - property: timeSlot
                      label: Créneau horaire
                      type: time
                    - property: reservationAt
                      label:  Date de réservation
                      type: date                           
            form:
                label: Réservation
                form_options: { validation_groups: [] }

                fields:
                    - property: user
                      label: Utilisateur
                    - property: Pseudo
                      label: Pseudo
                      type: text
                    - property: Score
                      label: Score
                      type: text
                    - property: timeSlot
                      label: Créneau horaire
                      type: time
                    - property: reservationAt
                      label:  Date de réservation
                      type: date                   
            edit:
                item_permission: 'ROLE_ADMIN'
            new:
                item_permission: 'ROLE_ADMIN'
            delete:
                item_permission: 'ROLE_ADMIN'


        Avatar:
            class: App\Entity\Avatar
            label: Avatar
            list:
                fields:
                    - property: title
                      label: Titre
                    - property: picture
                      label: Image
                      type: image
                      base_path: '/images/avatar/'
            form:
                label: Avatar
                form_options: { validation_groups: [] }
                fields:
                    - property: title
                      label: Titre
                    - property: picture
                      label: Image
                      type: file_upload
                      type_options:
                          upload_dir: public/images/avatar/ 
                               
            edit:
                item_permission: 'ROLE_ADMIN'
            new:
                item_permission: 'ROLE_ADMIN'                                                                             
            delete:
                item_permission: 'ROLE_ADMIN'


        CardGift:
           class: App\Entity\CardGift
           label: CarteGift
           list:
               fields:
                   - property: serial
                     label: Numéro de série                   
                   - property: gifts
                     label: Cadeau
                   - property: cards
                     label: Carte
                   - property: used
                     label: Utilisé

           form:
               label: CardGift
               form_options: { validation_groups: [] }
               fields:
                    - property: gifts
                      label: Cadeau
                    - property: cards
                      label: Carte                                            
           edit:
              item_permission: 'ROLE_ADMIN'
              fields:
                    - property: used
                      label: Utilisé
           new:
              item_permission: 'ROLE_ADMIN'
           delete:
              item_permission: 'ROLE_ADMIN'


    site_name: 'LaserWars'   
    design:
        menu:
          - { entity: 'User', icon: 'user' }
          - { entity: 'Ticket', icon: 'ticket' }
          - { entity: 'Gift', icon: 'gift' }
          - { entity: 'CardGift', icon: 'gift' }
          - { entity: 'Card', icon: 'credit-card' }
          - { entity: 'Booking', icon: 'id-card' }
          - { entity: 'Avatar', icon: 'user-circle' }