easy_admin:
    formats:
        date: 'd/m/Y'
        time: 'H:i'
        datetime: 'd/m/Y H:i:s'    
    entities:       
        User:
            class: App\Entity\User
            label: Utilisateur  
            list:
                item_permission: ROLE_ADMIN
                actions:
                    - { name: 'new', label: 'Ajouter', icon: 'plus' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - property: email
                      label: Email 
                    - property: lastName
                      label: Nom
                    - property: firstName
                      label: Prénom  
                    - property: side
                      label: side               
                    - property: birthdate
                      label: Date de naissance
                      type: date
                    - property: enabled
                      label: Compte activé
                    - property: createdAt
                      type: datetime
                      label: Date de création
                      type_options:
                        disabled: true
                        widget: single_text
                    - property: roles
                      label: Rôles                                      
            form:
                label: Utilisateur
                form_options: { validation_groups: [] }

                fields:
                    - property: email
                      label: Email
                    - property: lastName
                      label: Nom
                      type: text
                    - property: firstName
                      label: Prénom
                      type: text
                    - property: Side
                      label: Side
                      type: 'choice'
                      type_options:
                          mapped: true
                          choices: { 'Jedi': 'Jedi', 'Sith': 'Sith' }  
                    - property: birthdate
                      type: date
                      label: Date de naissance
                      type_options:
                        widget: single_text
                        input: datetime
                    - property: enabled
                      label: Compte activé
                    - property: 'roles' 
                      type: 'choice'
                      type_options:
                          mapped: true
                          expanded: true
                          multiple: true
                          choices: { 'Caissière': 'ROLE_CASHIER', 'Client': 'ROLE_USER', 'Administeur': 'ROLE_ADMIN' }                    
            edit:
                title: Modifier un utilisateur
                item_permission: 'ROLE_ADMIN'        
            new:
                title: Ajouter un utilisateur
                fields:
                    - property: password
                      type: text
                item_permission: 'ROLE_ADMIN'
            delete:
                title: Effacer un utilisateur
                item_permission: 'ROLE_ADMIN'


        Ticket:
            class: App\Entity\Ticket
            label: Billet
            list:
                actions:
                    - { name: 'new', label: 'Ajouter', icon: 'plus' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash'}                               
                fields:                    
                    - property: user
                      label: Utilisateur
                    - property: serial
                      label: Numéro de série                    
                    - property: buyAt
                      label: Date d'achat
                      type_options:
                        widget: single_text
                        input: datetime
                        disabled: true
                    - property: used
                      label: Utilisée
                      type: boolean                      
            form:
                label: Billet
                form_options: { validation_groups: [] }
                fields:
                    - property: user
                      label: Utilisateur    
            edit:
                title: Modifier un billet
                item_permission: ['ROLE_ADMIN', 'ROLE_CASHIER']
                fields: 
                    - property: used
                      label: Utilisée
            new:
                title: Ajouter un billet
                item_permission: ['ROLE_ADMIN', 'ROLE_CASHIER']
            delete:
                title: Effacer un billet
                item_permission: 'ROLE_ADMIN'                

        Gift:
            class: App\Entity\Gift
            label: Liste des cadeaux
            list:
                actions:
                    - { name: 'new', label: 'Ajouter', icon: 'plus' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - property: title
                      label: Titre
                    - property: category
                      label: Catégorie
                    - property: price
                      label: Prix
                    - property: picture
                      label: Image
                      type: image
                      base_path: '/images/gifts/'
            form:
                label: Cadeau
                form_options: { validation_groups: [] }
                fields:
                    - property: title
                      label: Titre
                    - property: category
                      label: Catégorie
                      type: 'choice'
                      type_options:
                          mapped: true
                          choices: { 'Friandises': 'Friandises', 'Costumes': 'Costumes' }  
                    - property: price
                      label: prix
                    - property: pictureFile
                      label: Image
                      type: file
                    - property: enabled
                      label: activé                                                         
            edit:
                title: Modifier un cadeau
                item_permission: 'ROLE_ADMIN'
            new:
                title: Ajouter un cadeau
                item_permission: 'ROLE_ADMIN'
            delete:
                title: Effacer un billet
                item_permission: 'ROLE_ADMIN'

        Card:
            class: App\Entity\Card
            label: Carte
            list:
                actions:
                    - { name: 'new', label: 'Ajouter', icon: 'plus' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - property: user
                      label: Utilisateur  
                    - property: serial
                      label: Numéro de série
                    - property: credits
                      label: Crédits
                    - property: expireCreditsAt
                      label: Date de expiration de crédit
                      type: date                                      
            form:
                label: carte
                form_options: { validation_groups: [] }
                fields:
                     - property: user
                       label: Utilisateur
                     - property: credits
                       label: Crédits                  
            edit:
                title: Modifier une carte
                item_permission: ['ROLE_ADMIN', 'ROLE_CASHIER']
            new:
                title: Ajouter une carte
                item_permission: ['ROLE_ADMIN', 'ROLE_CASHIER']
            delete:
                title: Effacer une carte
                item_permission: 'ROLE_ADMIN'                

        Booking:
            class: App\Entity\Booking
            label: Réservation
            list:
                actions:
                    - { name: 'new', label: 'Ajouter', icon: 'plus' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - property: user
                      label: Utilisateur
                    - property: serial
                      label: Numéro de série  
                    - property: Pseudo
                      label: Pseudo 
                      type: text
                    - property: Score
                      label: Score
                      type: text                    
                    - property: timeSlot
                      label: Créneau horaire
                      type: time
                    - property: reservationAt
                      label:  Date de réservation
                      type: date                           
            form:
                label: Réservation
                form_options: { validation_groups: [] }

                fields:
                    - property: user
                      label: Utilisateur
                    - property: Pseudo
                      label: Pseudo
                      type: text
                    - property: Score
                      label: Score
                      type: text
                    - property: timeSlot
                      label: Créneau horaire
                      type: time
                    - property: reservationAt
                      label:  Date de réservation
                      type: date                   
            edit:
                title: Modifier une réservation
                item_permission:  ['ROLE_ADMIN', 'ROLE_CASHIER']
            new:
                title: Ajouter une réservation
                item_permission:  ['ROLE_ADMIN', 'ROLE_CASHIER']
            delete:
                title: Effacer une réservation
                item_permission: 'ROLE_ADMIN'

        Avatar:
            class: App\Entity\Avatar
            label: Avatar
            list:
               actions:
                    - { name: 'new', label: 'Ajouter', icon: 'plus' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
               fields:
                    - property: title
                      label: Titre
                    - property: picture
                      label: Image
                      type: image
                      base_path: '/images/avatar/'
            form:
                label: Avatar
                form_options: { validation_groups: [] }
                fields:
                    - property: title
                      label: Titre                    
                    - property: pictureFile
                      label: Image
                      type: file                               
            edit:
                title: Modifier un avatar
                item_permission: 'ROLE_ADMIN'
            new:
                title: Ajouter un avatar
                item_permission: 'ROLE_ADMIN'                                                                             
            delete:
                title: Effacer un avatar
                item_permission: 'ROLE_ADMIN'


        CardGift:
            class: App\Entity\CardGift
            label: Cadeau des utilisateurs
            list:
                actions:
                    - { name: 'new', label: 'Ajouter', icon: 'plus' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - property: serial
                      label: Numéro de série                   
                    - property: gifts
                      label: Cadeau
                    - property: cards
                      label: Carte
                    - property: used
                      label: Utilisé
            form:
                label: CardGift
                form_options: { validation_groups: [] }
                fields:
                    - property: gifts
                      label: Cadeau
                    - property: cards
                      label: Carte                                            
            edit:
                title: Modifier un cadeau 
                item_permission:  ['ROLE_ADMIN']
                fields:
                    - property: used
                      label: Utilisé
            new:
                title: Ajouter un cadeau
                item_permission: ['ROLE_ADMIN', 'ROLE_CASHIER']
            delete:
                title: Effacer un cadeau
                item_permission: ['ROLE_ADMIN']

        Event:
            class: App\Entity\Event
            label: Evènement
            list:
                actions:
                    - { name: 'new', label: 'Ajouter', icon: 'plus' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - property: title
                      label: Titre   
                    - property: description
                      label: Description                 
                    - property: startEvent
                      label: Date de début
                    - property: endEvent
                      label: Date de fin
                    - property: multiplicator
                      label: Multiplicateur
            form:
                label: Event
                form_options: { validation_groups: [] }
                fields:
                    - property: title
                      label: Titre
                    - property: description
                      label: Description                     
                    - property: startEvent
                      label: Date de début
                      type: date
                    - property: endEvent
                      label: Date de fin
                      type: date
                    - property: multiplicator
                      label: Multiplicateur
            edit:
                title: Modifier un évènement 
                item_permission:  ['ROLE_ADMIN', 'ROLE_CASHIER']
            new:
                title: Ajouter un évènement 
                item_permission: ['ROLE_ADMIN', 'ROLE_CASHIER']
            delete:
                title: Effacer un évènement
                item_permission: ['ROLE_ADMIN']

        Contact:
            class: App\Entity\Contact
            label: Contact
            list:
                actions:
                    - { name: 'delete', label: '', icon: 'trash' }
                    - { name: '-new'}
                    - { name: '-edit'} 
                fields:
                    - property: email
                      label: Email   
                    - property: sujet
                      label: Sujet                 
                    - property: message
                      label: Message
            delete:
                title: Effacer un évènement
                item_permission: ['ROLE_ADMIN']            
 
    site_name: 'LaserWars'   
    design:
        menu:
          - { label: 'Retour sur le site', route: 'home', icon: 'arrow-left'}
          - { entity: 'Contact', icon: 'envelope'}
          - { label: 'Utilisateur' }
          - { entity: 'User', icon: 'user', permission: 'ROLE_ADMIN' }         
          - { entity: 'Avatar', icon: 'user-circle', permission: 'ROLE_ADMIN' }
          - { entity: 'Card', icon: 'credit-card' }
          - { label: 'Vente' }
          - { entity: 'Ticket', icon: 'ticket' }
          - { entity: 'Booking', icon: 'id-card' }
          - { label: 'Fidelité' }
          - { entity: 'Gift', icon: 'gift', permission: 'ROLE_ADMIN' }
          - { entity: 'CardGift', icon: 'gifts' }
          - { entity: 'Event', icon: 'calendar-alt' }          